### ISSUE TITLE
Unable to make on Manjaro 20.2.1

### ISSUE THREAD

**Issue by xunixorn** [zzag/kwin-effects-yet-another-magic-lamp#36]
when i try to `make` it fails and gives me this error:
```
Scanning dependencies of target kwin4_effect_yetanothermagiclamp_autogen
[  4%] Automatic MOC for target kwin4_effect_yetanothermagiclamp
AutoMoc warning
---------------
"SRC:/src/plugin.cc"
includes the moc file "plugin.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON, K_PLUGIN_CLASS_WITH_JSON, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[  4%] Built target kwin4_effect_yetanothermagiclamp_autogen
[  9%] Generating YetAnotherMagicLampConfig.h, YetAnotherMagicLampConfig.cpp
Scanning dependencies of target kwin4_effect_yetanothermagiclamp
[ 14%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp.o                                                                 
[ 19%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/Model.cc.o                                                 
[ 23%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/OffscreenRenderer.cc.o                                     
[ 28%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/WindowMeshRenderer.cc.o                                    
[ 33%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/YetAnotherMagicLampEffect.cc.o                             
[ 38%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/plugin.cc.o                                                
[ 42%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/YetAnotherMagicLampConfig.cpp.o                            
[ 47%] Linking CXX shared library libkwin4_effect_yetanothermagiclamp.so
/usr/bin/ld: CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/OffscreenRenderer.cc.o: in function `OffscreenRenderer::render(KWin::EffectWindow*)':
OffscreenRenderer.cc:(.text+0x1176): undefined reference to `epoxy_glClearColor'
/usr/bin/ld: OffscreenRenderer.cc:(.text+0x118c): undefined reference to `epoxy_glClear'
/usr/bin/ld: CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/WindowMeshRenderer.cc.o: in function `WindowMeshRenderer::render(KWin::EffectWindow*, QVector<WindowQuad> const&, KWin::GLTexture*, QRegion const&) const':
WindowMeshRenderer.cc:(.text+0x1319): undefined reference to `epoxy_glEnable'
/usr/bin/ld: WindowMeshRenderer.cc:(.text+0x1327): undefined reference to `epoxy_glEnable'
/usr/bin/ld: WindowMeshRenderer.cc:(.text+0x1335): undefined reference to `epoxy_glBlendFunc'
/usr/bin/ld: WindowMeshRenderer.cc:(.text+0x1380): undefined reference to `epoxy_glDisable'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:204: src/libkwin4_effect_yetanothermagiclamp.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:387: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

I am not sure what the problem is, but I checked, I have libepoxy 1.5.5-1 installed on Manjaro 20.2.1

**Comment by orychalk** [comment]
Hello,

Same problem for me on Manjaro 20.2.1 too :
`
':: Checking kwin-effects-yet-another-magic-lamp integrity...
==> Création du paquet kwin-effects-yet-another-magic-lamp 4.1.2-2 (sam. 23 janv. 2021 11:55:42)
==> Récupération des sources…
  -> kwin-effects-yet-another-magic-lamp-4.1.2.tar.gz trouvé
==> Validation des fichiers source avec sha256sums…
    kwin-effects-yet-another-magic-lamp-4.1.2.tar.gz ... Réussite
:: Preparing kwin-effects-yet-another-magic-lamp...
==> Création du paquet kwin-effects-yet-another-magic-lamp 4.1.2-2 (sam. 23 janv. 2021 11:55:43)
==> ATTENTION : Ignore la vérification des dépendances.
==> Récupération des sources…
  -> kwin-effects-yet-another-magic-lamp-4.1.2.tar.gz trouvé
==> ATTENTION : Ignore la vérification de l’intégrité de tous les fichiers sources.
==> Extraction des sources…
  -> Extraction de kwin-effects-yet-another-magic-lamp-4.1.2.tar.gz avec bsdtar
==> Lancement de prepare()…
==> Les sources sont prêtes.
:: Construction du paquet kwin-effects-yet-another-magic-lamp...
==> Création du paquet kwin-effects-yet-another-magic-lamp 4.1.2-2 (sam. 23 janv. 2021 11:55:45)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> ATTENTION : Utilisation de l’arbre $srcdir/ existant
==> Suppression du répertoire $pkgdir/ existant…
==> Lancement de build()…
-- The following OPTIONAL packages have been found:

 * KF5Auth (required version >= 5.78.0)
 * KF5Codecs (required version >= 5.78.0)
 * PkgConfig

-- The following REQUIRED packages have been found:

 * ECM
 * Qt5Gui
 * Qt5
 * Qt5DBus (required version >= 5.14.0)
 * KF5Config (required version >= 5.78.0)
 * KF5ConfigWidgets
 * Qt5Core (required version >= 5.14.0)
 * KF5CoreAddons
 * KF5WindowSystem
 * KF5
 * kwineffects
 * KWinDBusInterface
 * epoxy

-- Configuring done
-- Generating done
-- Build files have been written to: /home/pascal/.cache/pacaur/kwin-effects-yet-another-magic-lamp/src/build
[  9%] Automatic MOC for target kwin_yetanothermagiclamp_config
[  9%] Automatic MOC for target kwin4_effect_yetanothermagiclamp
AutoMoc warning
---------------
"SRC:/src/plugin.cc"
includes the moc file "plugin.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON, K_PLUGIN_CLASS_WITH_JSON, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[  9%] Built target kwin_yetanothermagiclamp_config_autogen
[  9%] Built target kwin4_effect_yetanothermagiclamp_autogen
[ 14%] Linking CXX shared library libkwin4_effect_yetanothermagiclamp.so
[ 61%] Built target kwin_yetanothermagiclamp_config
/usr/bin/ld : CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/OffscreenRenderer.cc.o : dans la fonction « OffscreenRenderer::render(KWin::EffectWindow*) » :
OffscreenRenderer.cc:(.text+0xf67) : référence indéfinie vers « epoxy_glClearColor »
/usr/bin/ld : OffscreenRenderer.cc:(.text+0xf7d) : référence indéfinie vers « epoxy_glClear »
/usr/bin/ld : CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/WindowMeshRenderer.cc.o : dans la fonction « WindowMeshRenderer::render(KWin::EffectWindow*, QVector<WindowQuad> const&, KWin::GLTexture*, QRegion const&) const » :
WindowMeshRenderer.cc:(.text+0x53b) : référence indéfinie vers « epoxy_glEnable »
/usr/bin/ld : WindowMeshRenderer.cc:(.text+0x549) : référence indéfinie vers « epoxy_glEnable »
/usr/bin/ld : WindowMeshRenderer.cc:(.text+0x557) : référence indéfinie vers « epoxy_glBlendFunc »
/usr/bin/ld : WindowMeshRenderer.cc:(.text+0x5a7) : référence indéfinie vers « epoxy_glDisable »
collect2: erreur: ld a retourné le statut de sortie 1
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:204 : src/libkwin4_effect_yetanothermagiclamp.so] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:387 : src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/all] Erreur 2
make: *** [Makefile:160 : all] Erreur 2
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…
:: failed to build kwin-effects-yet-another-magic-lamp package(s)
Press any key to continue...
`

Thanks

**Comment by Lapis-Apple** [comment]
Same problem.
[ 90%] Building CXX object src/kcm/CMakeFiles/kwin_yetanothermagiclamp_config.dir/kwineffects_interface.cpp.o
[ 95%] Linking CXX shared library libkwin4_effect_yetanothermagiclamp.so
/home/lapisapple/.cache/pikaur/build/kwin-effects-yet-another-magic-lamp/src/kwin-effects-yet-another-magic-lamp-4.1.2/src/kcm/YetAnotherMagicLampEffectKCM.cc: In constructor ‘YetAnotherMagicLampEffectKCM::YetAnotherMagicLampEffectKCM(QWidget*, const QVariantList&)’:
/home/lapisapple/.cache/pikaur/build/kwin-effects-yet-another-magic-lamp/src/kwin-effects-yet-another-magic-lamp-4.1.2/src/kcm/YetAnotherMagicLampEffectKCM.cc:29:28: warning: ‘static KAboutData* KAboutData::pluginData(const QString&)’ is deprecated: Since 5.76. See API docs [-Wdeprecated-declarations]
   29 |     : KCModule(KAboutData::pluginData(QStringLiteral("kwin4_effect_yetanothermagiclamp")), parent, args)
      |                            ^~~~~~~~~~
In file included from /usr/include/KF5/KCoreAddons/KAboutData:1,
                 from /home/lapisapple/.cache/pikaur/build/kwin-effects-yet-another-magic-lamp/src/kwin-effects-yet-another-magic-lamp-4.1.2/src/kcm/YetAnotherMagicLampEffectKCM.cc:26:
/usr/include/KF5/KCoreAddons/kaboutdata.h:467:24: note: declared here
  467 |     static KAboutData *pluginData(const QString &componentName);
      |                        ^~~~~~~~~~
/home/lapisapple/.cache/pikaur/build/kwin-effects-yet-another-magic-lamp/src/kwin-effects-yet-another-magic-lamp-4.1.2/src/kcm/YetAnotherMagicLampEffectKCM.cc:29:89: warning: ‘static KAboutData* KAboutData::pluginData(const QString&)’ is deprecated: Since 5.76. See API docs [-Wdeprecated-declarations]
   29 |     : KCModule(KAboutData::pluginData(QStringLiteral("kwin4_effect_yetanothermagiclamp")), parent, args)
      |                                                                                         ^
In file included from /usr/include/KF5/KCoreAddons/KAboutData:1,
                 from /home/lapisapple/.cache/pikaur/build/kwin-effects-yet-another-magic-lamp/src/kwin-effects-yet-another-magic-lamp-4.1.2/src/kcm/YetAnotherMagicLampEffectKCM.cc:26:
/usr/include/KF5/KCoreAddons/kaboutdata.h:467:24: note: declared here
  467 |     static KAboutData *pluginData(const QString &componentName);
      |                        ^~~~~~~~~~
/usr/bin/ld: CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/OffscreenRenderer.cc.o: in function `OffscreenRenderer::render(KWin::EffectWindow*)':
OffscreenRenderer.cc:(.text+0xf67): undefined reference to `epoxy_glClearColor'
/usr/bin/ld: OffscreenRenderer.cc:(.text+0xf7d): undefined reference to `epoxy_glClear'
/usr/bin/ld: CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/WindowMeshRenderer.cc.o: in function `WindowMeshRenderer::render(KWin::EffectWindow*, QVector<WindowQuad> const&, KWin::GLTexture*, QRegion const&) const':
WindowMeshRenderer.cc:(.text+0x53b): undefined reference to `epoxy_glEnable'
/usr/bin/ld: WindowMeshRenderer.cc:(.text+0x549): undefined reference to `epoxy_glEnable'
/usr/bin/ld: WindowMeshRenderer.cc:(.text+0x557): undefined reference to `epoxy_glBlendFunc'
/usr/bin/ld: WindowMeshRenderer.cc:(.text+0x5a7): undefined reference to `epoxy_glDisable'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:204: src/libkwin4_effect_yetanothermagiclamp.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:387: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX shared module kwin_yetanothermagiclamp_config.so
[100%] Built target kwin_yetanothermagiclamp_config
make: *** [Makefile:160: all] Error 2

Tested on my friend's computer(ArchLinux), same.

**Comment by trmdi** [comment]
Same here on openSUSE OBS, I don't know anything about CMake, but some how it will build if you change it like this: https://build.opensuse.org/package/view_file/home:trmdi/kwin-effects-yaml/add_header.patch?expand=1

**Comment by orychalk** [comment]
Hello trmdi,

Thanks for the answer, but I don't know how to use this patch (I don't have the knowledge in Linux patching).
Please, how can i must do ?

Thanks

**Comment by trmdi** [comment]
> Hello trmdi,
> 
> Thanks for the answer, but I don't know how to use this patch (I don't have the knowledge in Linux patching).
> Please, how can i must do ?
> 
> Thanks

I don't use Arch nowadays, but I think you can follow this: https://bbs.archlinux.org/viewtopic.php?id=229314

**Comment by orychalk** [comment]
Ok It's a good news, I will wait :)

Thanks

**Comment by zzag** [comment]
Ah, you build the effect against KF 5.78. It's a slightly different issue than the one fixed by 8e85583.

**Comment by trmdi** [comment]
Build failed on Leap: https://build.opensuse.org/package/live_build_log/home:trmdi/kwin-effects-yaml/openSUSE_Leap_15.2/x86_64

**Comment by zzag** [comment]
I can't maintain all plasma versions in master branch. If you want to build this effect against 5.20 or older, checkout Plasma/5.20 branch. master branch builds only with 5.21

**Comment by trmdi** [comment]
> I can't support all plasma versions in master branch. If you want to build this effect against 5.20 or older, checkout Plasma/5.20 branch. master branch builds only with 5.21

Ok, but could you please fix this? https://build.opensuse.org/package/live_build_log/home:trmdi/kwin-effects-yaml/openSUSE_Tumbleweed/x86_64
